"""The local, browser-driven hosting flow; all remote work stays server-side."""
import json


def render_hosting(csrf):
    return PAGE.replace('__HOSTING_CSRF__', json.dumps(csrf))


PAGE = r'''<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>Host your office — Worker Placement</title>
<style>
:root{color-scheme:dark;--bg:#0b1015;--panel:#121a22;--line:#27333f;--text:#edf2f5;--muted:#aab8c5;--green:#42dfb1}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:var(--green)}
.top{max-width:1120px;margin:auto;padding:24px 28px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);gap:16px}.brand{font-weight:750;color:var(--text);text-decoration:none}.local{font-size:11px;letter-spacing:.12em;color:var(--green);margin-left:12px}
main{max-width:1120px;margin:auto;padding:44px 28px 80px}.eyebrow{font-size:11px;letter-spacing:.16em;color:var(--green);font-weight:700}h1{font-size:clamp(32px,5vw,48px);line-height:1.12;letter-spacing:-.04em;margin:14px 0}h2{font-size:20px;margin:0 0 10px}h3{margin:0 0 8px;font-size:17px}p{margin:8px 0 18px;color:var(--muted)}.intro{max-width:660px;font-size:17px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 285px;gap:28px;margin-top:30px}.steps{display:flex;gap:20px;list-style:none;padding:0;margin:28px 0;color:var(--muted);font-size:13px}.steps span{display:inline-grid;place-items:center;border:1px solid var(--line);border-radius:50%;width:26px;height:26px;margin-right:7px}.steps .active{color:var(--green)}.steps .active span{border-color:var(--green)}
.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:25px;margin-bottom:16px}.card-head{display:flex;align-items:baseline;gap:12px}.number{color:var(--green);font-size:12px;font-weight:700}button,.button{display:inline-block;padding:11px 18px;border:1px solid var(--line);border-radius:8px;background:transparent;color:var(--text);font:inherit;font-size:14px;font-weight:650;cursor:pointer;text-decoration:none}button.primary,.button.primary{background:var(--green);border-color:var(--green);color:#062b20}button:disabled{opacity:.42;cursor:not-allowed}a:focus-visible,button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid var(--green);outline-offset:4px}.actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center}.fine{font-size:13px}.code{font:700 28px ui-monospace,monospace;letter-spacing:.16em;color:var(--text);padding:12px 0}.inset{margin:18px 0;padding:18px;border-left:3px solid var(--green);background:#0b141b}.stats{display:flex;flex-wrap:wrap;gap:28px;padding:16px 0}.stats strong{display:block;font-size:23px;color:var(--text)}.stats span{font-size:12px;color:var(--muted)}.files{list-style:none;padding:0;max-height:230px;overflow:auto}.files li{display:flex;gap:20px;justify-content:space-between;border-bottom:1px solid var(--line);padding:8px 0;font-size:12px}.files .path{overflow-wrap:anywhere}.files .size{white-space:nowrap;color:var(--muted)}details{margin:12px 0}summary{cursor:pointer;color:var(--green)}.replace{display:flex;align-items:flex-start;gap:10px;margin:18px 0;padding:15px;border:1px solid #76633f;border-radius:8px}.replace input{margin-top:6px}.replace small{display:block;color:var(--muted)}aside{padding:4px 0}aside h2{font-size:15px;margin-top:22px}aside p{font-size:13px}.success{border-color:var(--green)}.success h2{color:var(--green)}progress{width:100%;accent-color:var(--green);height:10px;margin:12px 0}.status{font-size:13px;min-height:1.6em}.status:not(:empty){margin-top:12px}[hidden]{display:none!important}
@media(max-width:780px){.layout{grid-template-columns:1fr}aside{display:grid;grid-template-columns:1fr 1fr;gap:20px}main{padding-top:28px}.local{display:none}}@media(max-width:440px){main,.top{padding-left:18px;padding-right:18px}.card{padding:19px}.steps{gap:10px;font-size:12px}.steps span{margin-right:4px}.top a:last-child{font-size:13px}aside{display:block}.actions button,.actions .button{width:100%;text-align:center}}
</style></head><body>
<header class="top"><a class="brand" href="/">worker placement.<span class="local">LOCAL OFFICE</span></a><a href="/">← Back to your office</a></header>
<main><div class="eyebrow">LOCAL → HOSTED</div><h1>Take your office online.</h1><p class="intro">Bring your saved accounts, commitments and retained research into a private hosted workspace. Your local copy stays right here.</p>
<ol class="steps" aria-label="Hosting steps"><li id="step-1" class="active"><span>1</span>Connect</li><li id="step-2"><span>2</span>Review</li><li id="step-3"><span>3</span>Upload</li></ol>
<div class="layout"><div>
<section class="card"><div class="card-head"><span class="number">01</span><h2>Connect your account</h2></div><p id="account">Sign in with email to choose where this office will live.</p><button id="login" type="button">Sign in with email ↗</button>
<div id="login-panel" class="inset" hidden><p>Open email sign-in, then approve this device only if the code matches:</p><div class="code" id="device-code"></div><a id="login-link" class="button primary" target="_blank" rel="noopener noreferrer">Open email sign-in ↗</a><p class="fine">After approving the device, return here. This page will update automatically. Signing in uploads nothing.</p></div><p class="status" id="login-status" role="status" aria-live="polite"></p></section>
<section class="card"><div class="card-head"><span class="number">02</span><h2>Review your saved files</h2></div><p>Check the office and documents before anything is uploaded.</p><button id="review" type="button" disabled>Review saved files</button><p class="status" id="review-status" role="status" aria-live="polite"></p>
<div id="preview" hidden><div class="inset"><h3 id="office-name"></h3><p class="fine" id="office-date"></p><p class="fine" id="destination"></p><div class="stats"><div><strong id="file-count"></strong><span>saved documents</span></div><div><strong id="file-bytes"></strong><span>total upload</span></div></div></div><details><summary>See included files</summary><ul class="files" id="files"></ul></details><p class="fine">Includes saved office data and supported retained documents. Credentials, generated pages and the Git checkout are excluded. The shared research library is already included in your hosted account.</p></div></section>
<section class="card" id="upload-card"><div class="card-head"><span class="number">03</span><h2>Host this snapshot</h2></div><p id="upload-copy">Your files are checked before the hosted snapshot becomes available. Later local changes are uploaded only when you choose.</p>
<label class="replace" id="replace-row" hidden><input type="checkbox" id="replace"><span>Replace the existing hosted snapshot<small id="replace-detail">The hosted copy will be updated with the files reviewed above. Your local office stays unchanged.</small></span></label>
<div class="actions"><button type="button" class="primary" id="upload" disabled>Upload my office</button><a class="button" id="open-existing" target="_blank" rel="noopener noreferrer" hidden>View current hosted copy ↗</a></div><progress id="progress" hidden></progress><p class="status" id="upload-status" role="status" aria-live="polite"></p></section>
<section id="complete" class="card success" hidden tabindex="-1"><div class="eyebrow">READY</div><h2>Your office is online.</h2><p>The saved files were verified and the hosted snapshot is ready. Your local office remains available.</p><a id="open-hosted" class="button primary" target="_blank" rel="noopener noreferrer">Open hosted office ↗</a><p class="fine">Keep editing locally. Use Review saved files when you want to upload a newer snapshot.</p></section>
<p id="fallback-error" role="alert" hidden></p>
</div><aside><div><h2>What’s available online?</h2><p>View your balances, goals and saved documents. Download individual files or export the complete office. Hosted editing and broker reconnects are still being built.</p></div><div><h2>Private to your account</h2><p>Your office is stored separately from the shared research library. Signing in alone does not upload any files.</p><h2>Your local copy stays yours</h2><p>This copies your saved office; it does not move or delete it. Unsaved form edits are not included. Each snapshot supports up to 64 MiB across 1,024 documents.</p></div></aside></div></main>
<script>
document.addEventListener('DOMContentLoaded',()=>{
const token=__HOSTING_CSRF__, $=id=>document.getElementById(id);let state={},previewId=null,finished=false,clientError=null;
const size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
function error(message){if(window.officeApiErrors)window.officeApiErrors.show('hosting','Hosting needs attention',message);else{$('fallback-error').textContent=message;$('fallback-error').hidden=false;}}
function clearError(){if(window.officeApiErrors)window.officeApiErrors.clear('hosting');$('fallback-error').hidden=true;}
async function request(action,payload){const options={headers:{'X-Office-Hosting':token},cache:'no-store'};if(payload!==undefined){options.method='POST';options.headers['Content-Type']='application/json';options.body=JSON.stringify(payload);}const response=await fetch('/hosting/'+action,options);const result=await response.json();if(!response.ok)throw new Error(result.error||'This action could not be completed. Try again.');return result;}
function render(s){state=s;if(s.error||clientError)error(s.error||clientError);else clearError();const p=s.preview,busy=s.busy;
$('account').textContent=s.connected?'Signed in as '+s.email:'Sign in with email to choose where this office will live.';$('login').textContent=s.connected?'Use a different account':'Sign in with email ↗';$('login').disabled=busy;
$('login-panel').hidden=s.phase!=='authorizing';if(s.login_url){$('login-link').href=s.login_url;$('device-code').textContent=s.code;}
$('login-status').textContent=s.phase==='connecting'?'Preparing secure sign-in…':s.phase==='authorizing'?'Waiting for you to approve this device…':s.phase==='connected'?'Connected. Review the files to continue.':'';
$('review').disabled=!s.connected||busy;$('review').textContent=p?'Review saved files again':'Review saved files';$('review-status').textContent=s.phase==='reviewing'?'Checking saved files and the hosted destination…':'';$('preview').hidden=!p;
if(p&&previewId!==p.id){previewId=p.id;$('replace').checked=false;$('office-name').textContent=p.name;$('office-date').textContent='Saved balances as of '+p.as_of;$('destination').textContent='Private destination: '+p.email;$('file-count').textContent=p.files.length;$('file-bytes').textContent=size(p.bytes);$('files').replaceChildren();for(const f of p.files){const row=document.createElement('li'),name=document.createElement('span'),bytes=document.createElement('span');name.className='path';name.textContent=f.path;bytes.className='size';bytes.textContent=size(f.size);row.append(name,bytes);$('files').append(row);}}
$('replace-row').hidden=!p||!p.replace_required;$('upload').disabled=!p||!s.connected||busy||s.phase==='complete'||(p.replace_required&&!$('replace').checked);$('upload').textContent=s.phase==='error'?'Retry upload':p&&p.replace_required?'Replace hosted snapshot':'Upload my office';
$('upload-copy').textContent=p&&p.already_hosted?'These saved files already match your hosted snapshot. You can open it below or verify the upload again.':'Your files are checked before the hosted snapshot becomes available. Later local changes are uploaded only when you choose.';
$('open-existing').hidden=!s.url||s.phase==='complete';if(s.url){$('open-existing').href=s.url;$('open-hosted').href=s.url;}
const transferring=['uploading','verifying'].includes(s.phase);$('progress').hidden=!transferring;if(s.total){$('progress').max=s.total;$('progress').value=s.done;}else $('progress').removeAttribute('value');
$('upload-status').textContent=s.phase==='uploading'?(s.total?'Uploading '+s.done+' of '+s.total+' parts…':'Preparing the reviewed upload…'):s.phase==='verifying'?'Verifying files and opening the hosted snapshot…':'';
$('complete').hidden=s.phase!=='complete';if(s.phase==='complete'&&!finished){$('complete').focus();finished=true;}if(s.phase!=='complete')finished=false;
const step=s.phase==='complete'||transferring?3:p||s.connected?2:1;[1,2,3].forEach(n=>{$('step-'+n).classList.toggle('active',n===step);if(n===step)$('step-'+n).setAttribute('aria-current','step');else $('step-'+n).removeAttribute('aria-current');});}
async function act(action,payload={}){try{clientError=null;render({...state,busy:true,error:null});render(await request(action,payload));}catch(e){clientError=e.message;render({...state,busy:false});}}
$('login').onclick=()=>act('login');$('review').onclick=()=>act('review');$('replace').onchange=()=>render(state);$('upload').onclick=()=>act('upload',{preview:state.preview.id,replace:$('replace').checked});
async function poll(){try{render(await request('status'));}catch(e){error('Could not reach the local app. Keep it running, then reload this page.');}setTimeout(poll,2000);}poll();
});
</script></body></html>'''
