"""Synthesize survivorship-bias backtest results.

Reads each pilot_<TICKER>.json under scores/, runs deterministic composite
recompute, joins with forward returns, and computes:

  - Per-name composite + recomputed composite + tier
  - SHORT-flag hit rate (catastrophes correctly flagged)
  - False-positive rate (positive-returners wrongly flagged)
  - Basket P&L: equal-weight SHORT-tier vs IWM
  - Stratified by group (delisted_or_distressed vs control_survivor)

Usage:
    python3 verticals/public_co/data/_backtest/survivorship_2025_05/synthesize.py
"""
import json
import statistics
from pathlib import Path

HERE = Path(__file__).parent
SCORES = HERE / "scores"
# Measurement reads from the unblinded source (contains forward_return).
# Agent-facing scripts must read from HERE / "combined_test_set.json" instead,
# which is the leak-stripped view generated by build_blinded.py.
TEST_SET = HERE / "_unblinded" / "combined_test_set.json"

SEV_W = {
    "PASS": 0,
    "UNVERIFIABLE": 0,
    "MODERATE_UNDERDELIVERY": 1,
    "SEVERE_UNDERDELIVERY": 2,
    "RED_FLAG_NEGATIVE": 3,
}


def tier(composite: float) -> str:
    if composite <= 0.20:
        return "STRICT_LONG"
    if composite <= 0.30:
        return "LOOSE_LONG"
    if composite < 0.50:
        return "NEUTRAL"
    return "SHORT"


def main():
    test_set = {r["ticker"]: r for r in json.loads(TEST_SET.read_text())}
    rows = []
    unscoreable = []
    for f in sorted(SCORES.glob("pilot_*.json")):
        d = json.loads(f.read_text())
        tk = d.get("ticker") or f.stem.replace("pilot_", "")
        tuples = d.get("rfm_tuples") or []
        ts = test_set.get(tk, {})
        fwd = ts.get("forward_return")
        if not tuples:
            unscoreable.append({
                "ticker": tk,
                "reason": d.get("exclusion_reason", "no_tuples"),
                "forward_return": fwd,
            })
            continue
        counts = {k: 0 for k in SEV_W}
        for t in tuples:
            s = t.get("severity")
            if s in counts:
                counts[s] += 1
        composite = sum(SEV_W[k] * v for k, v in counts.items()) / len(tuples)
        rows.append({
            "ticker": tk,
            "company": ts.get("company") or d.get("company"),
            "group": ts.get("group") or d.get("group"),
            "composite_recomputed": composite,
            "composite_agent_reported": d.get("composite"),
            "tier": tier(composite),
            "n_claims": len(tuples),
            "sev_counts": counts,
            "forward_return": fwd,
            "delisted": ts.get("delisted", False),
            "summary": d.get("summary", "")[:500],
        })

    rows.sort(key=lambda x: -x["composite_recomputed"])

    print("=" * 96)
    print(f"SURVIVORSHIP-BIAS BACKTEST RESULTS — {len(rows)} pilots")
    print(f"  Cutoff: 2025-05-15  |  Measurement: 2026-05-15")
    print("=" * 96)
    print()
    print(f"{'TK':6} {'comp':>5}  {'tier':12}  {'fwd':>8}  {'group':25}  {'sev':18}")
    print("-" * 96)
    for r in rows:
        fwd = r["forward_return"]
        fwd_s = f"{fwd*100:+.1f}%" if fwd is not None else "  null"
        sc = r["sev_counts"]
        sev = f"P{sc['PASS']}/M{sc['MODERATE_UNDERDELIVERY']}/S{sc['SEVERE_UNDERDELIVERY']}/R{sc['RED_FLAG_NEGATIVE']}/U{sc['UNVERIFIABLE']}"
        print(f"{r['ticker']:6} {r['composite_recomputed']:>5.3f}  {r['tier']:12}  {fwd_s:>8}  {r['group']:25}  {sev:18}")

    print()
    print("=" * 96)
    print("HIT RATE: did the framework SHORT-flag the catastrophes?")
    print("=" * 96)

    catastrophes = [r for r in rows if (r["forward_return"] or 0) <= -0.40]
    short_flagged = [r for r in rows if r["tier"] == "SHORT"]
    catastrophes_flagged = [r for r in catastrophes if r["tier"] == "SHORT"]
    print(f"  Catastrophes (return <= -40%): {len(catastrophes)}")
    print(f"  SHORT-flagged total: {len(short_flagged)}")
    print(f"  SHORT-flagged catastrophes (true positives): {len(catastrophes_flagged)}")
    if catastrophes:
        print(f"  Catastrophe SHORT-flag hit rate: {len(catastrophes_flagged)/len(catastrophes)*100:.0f}%")
    if short_flagged:
        print(f"  Short precision (TP / all SHORT-flagged): {len(catastrophes_flagged)/len(short_flagged)*100:.0f}%")

    print()
    print("FALSE POSITIVES (SHORT-flagged but positive forward return):")
    fps = [r for r in rows if r["tier"] == "SHORT" and (r["forward_return"] or 0) > 0.10]
    for r in fps:
        print(f"  {r['ticker']:6} comp={r['composite_recomputed']:.3f}  fwd={r['forward_return']*100:+.1f}%")

    print()
    print("FALSE NEGATIVES (catastrophes missed by framework — LONG/NEUTRAL):")
    fns = [r for r in catastrophes if r["tier"] != "SHORT"]
    for r in fns:
        print(f"  {r['ticker']:6} comp={r['composite_recomputed']:.3f}  fwd={r['forward_return']*100:+.1f}%  tier={r['tier']}")

    print()
    print("=" * 96)
    print("BASKET P&L")
    print("=" * 96)
    short_rets = [r["forward_return"] for r in short_flagged if r["forward_return"] is not None]
    long_safe_rets = [r["forward_return"] for r in rows if r["tier"] != "SHORT" and r["forward_return"] is not None]
    strict_long_rets = [r["forward_return"] for r in rows if r["tier"] == "STRICT_LONG" and r["forward_return"] is not None]
    loose_long_rets = [r["forward_return"] for r in rows if r["tier"] in ("STRICT_LONG", "LOOSE_LONG") and r["forward_return"] is not None]

    # Survivorship-aware "true universe" baseline: every test-set name with a valid forward return,
    # whether scored or not (and whether scoreable or not). This is what IWM-equivalent ownership
    # would have produced over the same window.
    universe_rets = [r["forward_return"] for r in test_set.values() if r.get("forward_return") is not None]
    scored_rets = [r["forward_return"] for r in rows if r["forward_return"] is not None]
    unscoreable_rets = [u["forward_return"] for u in unscoreable if u.get("forward_return") is not None]

    def line(label, rets):
        if not rets:
            return
        print(f"  {label:34} n={len(rets):3}  mean={statistics.mean(rets)*100:+7.1f}%  median={statistics.median(rets)*100:+7.1f}%")

    print("  Framework baskets (scored only):")
    line("STRICT_LONG basket",       strict_long_rets)
    line("LOOSE_LONG (incl strict)", loose_long_rets)
    line("NOT-SHORT basket",         long_safe_rets)
    line("SHORT basket (avoided)",   short_rets)
    print()
    print("  Baselines:")
    line("SCORED-ONLY basket",       scored_rets)
    line("FULL UNIVERSE (survivorship-aware)", universe_rets)
    if unscoreable_rets:
        line("UNSCOREABLE basket",   unscoreable_rets)

    # Alpha vs the right benchmark
    if loose_long_rets and universe_rets:
        alpha = statistics.mean(loose_long_rets) - statistics.mean(universe_rets)
        print(f"\n  ALPHA: LOOSE_LONG basket vs full survivorship-aware universe = {alpha*100:+.1f} pp")
    if short_rets and universe_rets:
        short_alpha = statistics.mean(universe_rets) - statistics.mean(short_rets)
        print(f"  AVOIDANCE-ALPHA: skipping SHORT basket vs full universe = {short_alpha*100:+.1f} pp")

    # Per-group stratification
    print()
    print("STRATIFIED BY GROUP")
    for g in ("delisted_or_distressed", "control_survivor"):
        grows = [r for r in rows if r["group"] == g]
        cats = [r for r in grows if (r["forward_return"] or 0) <= -0.40]
        cflags = [r for r in cats if r["tier"] == "SHORT"]
        print(f"  {g}: n={len(grows)}, catastrophes={len(cats)}, flagged={len(cflags)} ({len(cflags)/max(1,len(cats))*100:.0f}%)")

    # Save synthesis JSON
    out = HERE / "synthesis.json"
    out.write_text(json.dumps(rows, indent=2))
    print(f"\nSaved synthesis to {out}")


if __name__ == "__main__":
    main()
